using System;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Nexus.Core;
using RingFlow.Gameplay;
using RingFlow.Gameplay.UI;
using Object = UnityEngine.Object;

namespace RingFlow.Editor
{
    /// <summary>
    /// Custom Inspector for all RingFlow UI View components (HUDView, WinView,
    /// PauseView, etc.). Adds a "Populate UI References" button that calls the
    /// View's private <see cref="BindReferencesFromChildren"/> method, automatically
    /// filling every [SerializeField] field (buttons, texts, images) by scanning
    /// the prefab's child hierarchy.
    ///
    /// After BindReferencesFromChildren runs, a <see cref="SmartFallbackPopulate"/>
    /// pass fills any remaining null references using type-based hierarchy search,
    /// so fields with mismatched naming conventions still get populated.
    ///
    /// This guarantees that prefabs generated by <see cref="UIPrefabBuilder"/> have
    /// all serialized references populated at design time, so runtime Awake()
    /// never encounters null references even when the UI was built programmatically.
    ///
    /// Use the "Nexus > Populate All UI References" menu item to batch-process
    /// every screen prefab in one click.
    /// </summary>
    [CustomEditor(typeof(View), true)]
    [CanEditMultipleObjects]
    public class UIViewEditor : UnityEditor.Editor
    {
        private static readonly BindingFlags k_bindingFlags =
            BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public;

        private bool _hadNullRefs;

        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            Type type = target.GetType();
            if (!HasBindReferencesMethod(type))
                return;

            // Cache null-state per frame to avoid repeated reflection
            if (Event.current.type == EventType.Layout)
                _hadNullRefs = HasAnyNullSerializedField(target);

            EditorGUILayout.Space(8f);
            EditorGUILayout.LabelField("UI Reference Populator", EditorStyles.boldLabel);

            if (_hadNullRefs)
            {
                EditorGUILayout.HelpBox(
                    "Some serialized references are null. Click below to auto-populate " +
                    "them from the prefab's child hierarchy.",
                    MessageType.Warning);
            }
            else
            {
                EditorGUILayout.HelpBox("All serialized references appear to be populated.", MessageType.Info);
            }

            EditorGUILayout.BeginHorizontal();
            GUI.enabled = _hadNullRefs;
            if (GUILayout.Button("Populate UI References", GUILayout.Height(30)))
            {
                foreach (Object t in targets)
                {
                    Undo.RecordObject(t, "Populate UI References");
                    InvokeBindReferences(t);
                    SmartFallbackPopulate(t);
                }
            }
            GUI.enabled = true;

            if (GUILayout.Button("Force Repopulate", GUILayout.Height(30)))
            {
                foreach (Object t in targets)
                {
                    Undo.RecordObject(t, "Force Populate UI References");
                    InvokeBindReferences(t);
                    SmartFallbackPopulate(t);
                }
            }
            EditorGUILayout.EndHorizontal();

            EditorGUILayout.Space(4f);
        }

        // ── Reflection Helpers ──────────────────────────────────────────

        private static bool HasBindReferencesMethod(Type type)
        {
            return type.GetMethod("BindReferencesFromChildren", k_bindingFlags) != null;
        }

        /// <summary>
        /// Checks whether any [SerializeField] field declared on the target's
        /// own type is null. Only considers fields declared directly on the
        /// View subclass, not inherited from View / MonoBehaviour.
        /// </summary>
        private static bool HasAnyNullSerializedField(Object obj)
        {
            if (obj == null) return true;
            Type type = obj.GetType();
            FieldInfo[] fields = type.GetFields(BindingFlags.Instance |
                                                 BindingFlags.NonPublic |
                                                 BindingFlags.Public |
                                                 BindingFlags.DeclaredOnly);

            foreach (FieldInfo field in fields)
            {
                if (!field.IsPublic && field.GetCustomAttribute<SerializeField>() == null)
                    continue;

                object val = field.GetValue(obj);
                if (val == null) return true;

                if (val is Array arr)
                {
                    for (int i = 0; i < arr.Length; i++)
                    {
                        if (arr.GetValue(i) == null) return true;
                    }
                }
            }
            return false;
        }

        /// <summary>
        /// Calls BindReferencesFromChildren via reflection. No undo recording
        /// — caller is responsible for that if needed.
        /// </summary>
        internal static void InvokeBindReferences(Object obj)
        {
            Type type = obj.GetType();
            MethodInfo method = type.GetMethod("BindReferencesFromChildren", k_bindingFlags);
            if (method == null)
            {
                Debug.LogWarning("[UIViewEditor] No BindReferencesFromChildren found on " + type.Name, obj);
                return;
            }

            method.Invoke(obj, null);
            EditorUtility.SetDirty(obj);
            PrefabUtility.RecordPrefabInstancePropertyModifications(obj);

            Debug.Log("[UIViewEditor] Populated references for " + obj.name + " (" + type.Name + ")", obj);
        }

        // ══════════════════════════════════════════════════════════════════
        //  SMART FALLBACK — type-based hierarchy search for null fields
        // ══════════════════════════════════════════════════════════════════

        /// <summary>
        /// After BindReferencesFromChildren() has run, find any remaining null
        /// [SerializeField] fields and try to populate them by searching the
        /// child hierarchy for components of the matching type.
        ///
        /// Strategy per type:
        ///   - CanvasGroup, Slider, TMP_Dropdown: unique per View — assign first found.
        ///   - Button, Toggle: match by name using field name as hint (strip leading '_').
        ///   - TextMeshProUGUI, Image: match by name using field name as hint.
        ///   - Component[] arrays: match elements by index via name heuristics.
        /// </summary>
        private static void SmartFallbackPopulate(Object obj)
        {
            if (obj == null) return;

            Component component = obj as Component;
            if (component == null) return;

            GameObject go = component.gameObject;
            Type type = obj.GetType();
            int assignedCount = 0;
            int convertedCount = 0;

            // PHASE 1: Upgrade legacy Text → TextMeshProUGUI and Dropdown → TMP_Dropdown
            convertedCount = UpgradeLegacyComponents(go.transform);

            // PHASE 2: Build type map from the (now upgraded) hierarchy
            var typeMap = BuildComponentTypeMap(go.transform);

            FieldInfo[] fields = type.GetFields(BindingFlags.Instance |
                                                 BindingFlags.NonPublic |
                                                 BindingFlags.Public |
                                                 BindingFlags.DeclaredOnly);

            foreach (FieldInfo field in fields)
            {
                if (!field.IsPublic && field.GetCustomAttribute<SerializeField>() == null)
                    continue;

                // Skip non-Component fields (int, string, bool, etc.)
                if (!typeof(Component).IsAssignableFrom(field.FieldType) &&
                    !(field.FieldType.IsArray &&
                      typeof(Component).IsAssignableFrom(field.FieldType.GetElementType())))
                    continue;

                object currentVal = field.GetValue(obj);

                // Handle arrays
                if (field.FieldType.IsArray)
                {
                    Type elementType = field.FieldType.GetElementType();
                    Array arr = currentVal as Array;
                    if (arr == null) continue;

                    if (!typeMap.TryGetValue(elementType, out var candidates)) continue;

                    for (int i = 0; i < arr.Length; i++)
                    {
                        if (arr.GetValue(i) != null) continue;

                        foreach (var cand in candidates)
                        {
                            bool nameMatch = i < 9 && cand.name.ToUpperInvariant().EndsWith((i + 1).ToString());
                            if (nameMatch && !IsAlreadyInArray(arr, cand))
                            {
                                arr.SetValue(cand, i);
                                assignedCount++;
                                break;
                            }
                        }
                    }
                    field.SetValue(obj, arr);
                    continue;
                }

                // Single Component fields
                if (currentVal != null) continue;

                string fieldHint = field.Name.TrimStart('_').ToUpperInvariant();

                // Unique per-View types: assign first found
                if (field.FieldType == typeof(CanvasGroup) ||
                    field.FieldType == typeof(Slider) ||
                    field.FieldType == typeof(TMP_Dropdown))
                {
                    if (typeMap.TryGetValue(field.FieldType, out var uniqueCands) && uniqueCands.Count > 0)
                    {
                        field.SetValue(obj, uniqueCands[0]);
                        assignedCount++;
                    }
                    continue;
                }

                // Types with multiple candidates: match by name
                if (!typeMap.TryGetValue(field.FieldType, out var comps))
                    continue;

                // Extract keywords from field name: strip leading '_', remove common suffixes
                string keywords = StripCommonSuffixes(fieldHint);

                Component bestMatch = null;
                int bestScore = 0;

                foreach (var comp in comps)
                {
                    string compName = comp.name.ToUpperInvariant();
                    int score = 0;

                    // Exact match on whole field hint
                    if (compName.Contains(fieldHint)) score += 100;
                    // Keyword match
                    if (compName.Contains(keywords)) score += 80;
                    // Button prefix handling
                    string stripped = compName.Replace("BTN_", "").Replace("_BUTTON", "");
                    if (fieldHint.Contains(stripped) || stripped.Contains(fieldHint)) score += 50;
                    if (stripped.Contains(keywords)) score += 40;
                    // Partial match: check word boundaries
                    if (keywords.Length >= 3)
                    {
                        for (int k = 0; k <= keywords.Length - 3; k++)
                        {
                            string segment = keywords.Substring(k, 3);
                            if (compName.Contains(segment)) score += 5;
                        }
                    }

                    // Known abbreviation fallback: "LEVEL" ↔ "LV" / "LVL"
                    if (fieldHint.Contains("LEVEL") && (compName == "LV" || compName.Contains("LVTEXT") || compName == "LVL")) score += 60;
                    // Known abbreviation fallback: "PLAYER" ↔ "PL" / "PV" 
                    if (fieldHint.Contains("PLAYER") && compName.Contains("LV")) score += 30;

                    if (score > bestScore)
                    {
                        bestScore = score;
                        bestMatch = comp;
                    }
                }

                if (bestMatch != null && bestScore > 0)
                {
                    field.SetValue(obj, bestMatch);
                    assignedCount++;
                }
            }

            if (assignedCount > 0 || convertedCount > 0)
            {
                EditorUtility.SetDirty(obj);
                PrefabUtility.RecordPrefabInstancePropertyModifications(obj);
                string msg = $"[UIViewEditor] SmartFallback: converted {convertedCount}, assigned {assignedCount} reference(s) for {obj.name} ({type.Name})";
                if (convertedCount > 0) Debug.Log(msg); else Debug.Log(msg, obj);
            }

            // Log component census for debugging null-field issues (only if nothing was assigned)
            if (assignedCount == 0 && convertedCount == 0 && typeMap.Count > 0)
            {
                string totalComps = "";
                foreach (var kvp in typeMap)
                    totalComps += $"{kvp.Key.Name}:{kvp.Value.Count} ";
                Debug.Log($"[UIViewEditor] Components found for {obj.name}: {totalComps.Trim()}");
            }
        }

        /// <summary>
        /// Upgrades legacy Text → TextMeshProUGUI and Dropdown → TMP_Dropdown
        /// across the entire prefab hierarchy. Returns count of upgraded components.
        /// </summary>
        private static int UpgradeLegacyComponents(Transform root)
        {
            int count = 0;
            UpgradeRecursive(root, ref count);
            return count;
        }

        private static void UpgradeRecursive(Transform t, ref int count)
        {
            // Upgrade legacy Text → TextMeshProUGUI
            var legacyText = t.GetComponent<Text>();
            if (legacyText != null)
            {
                string txt = legacyText.text;
                int fontSize = legacyText.fontSize;
                Color color = legacyText.color;
                bool supportRich = legacyText.supportRichText;
                bool bestFit = legacyText.resizeTextForBestFit;
                int minSize = legacyText.resizeTextMinSize;
                int maxSize = legacyText.resizeTextMaxSize;
                FontStyle fStyle = legacyText.fontStyle;
                TextAnchor alignment = legacyText.alignment;
                float lineSpacing = legacyText.lineSpacing;
                bool raycast = legacyText.raycastTarget;
                string name = legacyText.name;

                Object.DestroyImmediate(legacyText, true);

                var tmp = t.gameObject.AddComponent<TextMeshProUGUI>();
                tmp.text = txt;
                // Legacy Text.fontSize uses pixels at em-size (~14-16).
                // TMP uses point-based sizing — multiply by ~1.8 for visual parity.
                tmp.fontSize = Mathf.RoundToInt(fontSize * 2.0f);
                tmp.color = color;
                tmp.richText = supportRich;
                tmp.enableAutoSizing = bestFit;
                if (bestFit) { tmp.fontSizeMin = minSize; tmp.fontSizeMax = maxSize; }
                tmp.raycastTarget = raycast;
                tmp.lineSpacing = lineSpacing;
                // Map FontStyle
                tmp.fontStyle = fStyle == FontStyle.Bold ? FontStyles.Bold :
                                fStyle == FontStyle.Italic ? FontStyles.Italic :
                                fStyle == FontStyle.BoldAndItalic ? FontStyles.Bold | FontStyles.Italic :
                                FontStyles.Normal;
                // Map TextAnchor to TextAlignmentOptions (approximate)
                tmp.alignment = alignment switch
                {
                    TextAnchor.UpperLeft => TextAlignmentOptions.TopLeft,
                    TextAnchor.UpperCenter => TextAlignmentOptions.Top,
                    TextAnchor.UpperRight => TextAlignmentOptions.TopRight,
                    TextAnchor.MiddleLeft => TextAlignmentOptions.Left,
                    TextAnchor.MiddleCenter => TextAlignmentOptions.Center,
                    TextAnchor.MiddleRight => TextAlignmentOptions.Right,
                    TextAnchor.LowerLeft => TextAlignmentOptions.BottomLeft,
                    TextAnchor.LowerCenter => TextAlignmentOptions.Bottom,
                    TextAnchor.LowerRight => TextAlignmentOptions.BottomRight,
                    _ => TextAlignmentOptions.Center
                };
                count++;
            }

            // Upgrade legacy Dropdown → TMP_Dropdown
            var legacyDropdown = t.GetComponent<Dropdown>();
            if (legacyDropdown != null)
            {
                bool interactable = legacyDropdown.interactable;
                Object.DestroyImmediate(legacyDropdown, true);
                var tmpDd = t.gameObject.AddComponent<TMP_Dropdown>();
                tmpDd.interactable = interactable;
                count++;
            }

            // Upgrade legacy InputField → TMP_InputField
            var legacyInput = t.GetComponent<InputField>();
            if (legacyInput != null)
            {
                bool interactable2 = legacyInput.interactable;
                string inputText = legacyInput.text;
                Object.DestroyImmediate(legacyInput, true);
                var tmpInput = t.gameObject.AddComponent<TMP_InputField>();
                tmpInput.interactable = interactable2;
                tmpInput.text = inputText;
                count++;
            }

            for (int i = 0; i < t.childCount; i++)
                UpgradeRecursive(t.GetChild(i), ref count);
        }

        /// <summary>
        /// Walks the entire Transform hierarchy and builds a map: ComponentType → List<Component>.
        /// Uses non-generic GetComponent(Type) so it works reliably on prefab-contents GameObjects.
        /// </summary>
        private static System.Collections.Generic.Dictionary<Type, System.Collections.Generic.List<Component>> BuildComponentTypeMap(Transform root)
        {
            var map = new System.Collections.Generic.Dictionary<Type, System.Collections.Generic.List<Component>>();
            WalkTransform(root, map);
            return map;
        }

        private static void WalkTransform(Transform t, System.Collections.Generic.Dictionary<Type, System.Collections.Generic.List<Component>> map)
        {
            foreach (var comp in t.GetComponents<Component>())
            {
                if (comp == null) continue;
                Type ct = comp.GetType();
                if (!map.TryGetValue(ct, out var list))
                {
                    list = new System.Collections.Generic.List<Component>();
                    map[ct] = list;
                }
                list.Add(comp);
            }
            for (int i = 0; i < t.childCount; i++)
                WalkTransform(t.GetChild(i), map);
        }

        private static string StripCommonSuffixes(string hint)
        {
            string[] suffixes = { "BUTTON", "TEXT", "LABEL", "IMAGE", "ICON", "SLIDER", "TOGGLE", "DROPDOWN", "GROUP" };
            string result = hint;
            foreach (var sfx in suffixes)
            {
                if (result.EndsWith(sfx) && result.Length > sfx.Length)
                {
                    result = result.Substring(0, result.Length - sfx.Length);
                    break;
                }
            }
            return result;
        }

        private static bool IsAlreadyInArray(Array arr, Component cand)
        {
            for (int i = 0; i < arr.Length; i++)
                if ((Object)arr.GetValue(i) == (Object)cand) return true;
            return false;
        }

        /// <summary>
        /// Returns a comma-separated list of null [SerializeField] field names, or empty if all are populated.
        /// </summary>
        private static string GetNullFieldReportString(Object obj)
        {
            if (obj == null) return "obj is null";
            Type type = obj.GetType();
            var nullFields = new System.Collections.Generic.List<string>();

            FieldInfo[] fields = type.GetFields(BindingFlags.Instance |
                                                 BindingFlags.NonPublic |
                                                 BindingFlags.Public |
                                                 BindingFlags.DeclaredOnly);

            foreach (FieldInfo field in fields)
            {
                if (!field.IsPublic && field.GetCustomAttribute<SerializeField>() == null)
                    continue;

                object val = field.GetValue(obj);
                if (val == null)
                {
                    nullFields.Add(field.Name);
                }
                else if (val is Array arr)
                {
                    for (int i = 0; i < arr.Length; i++)
                    {
                        if (arr.GetValue(i) == null)
                        {
                            nullFields.Add($"{field.Name}[{i}]");
                        }
                    }
                }
            }

            return nullFields.Count > 0 ? string.Join(", ", nullFields) : string.Empty;
        }

        // ══════════════════════════════════════════════════════════════════
        //  BATCH POPULATOR (Menu Item)
        // ══════════════════════════════════════════════════════════════════

        [MenuItem("Nexus/Populate All UI References", priority = 120)]
        private static void PopulateAllScreenPrefabs()
        {
            if (!EditorUtility.DisplayDialog("Populate All UI References",
                    "This will scan all screen prefabs and populate " +
                    "all serialized references by calling BindReferencesFromChildren() on each View.\n\n" +
                    "Proceed?", "Continue", "Cancel"))
                return;

            // Initialize theme so GameUIResources.AddButtonEffects doesn't NRE
            var theme = Resources.Load<UIThemeConfigSO>(GameplayAssetKeys.UIThemeConfig);
            if (theme != null)
                GameUIResources.Bind(theme);

            ScreenType[] screenTypes = (ScreenType[])Enum.GetValues(typeof(ScreenType));
            int populated = 0;
            int skipped = 0;
            int errors = 0;

            foreach (ScreenType screen in screenTypes)
            {
                string prefabPath = RingFlowEditorUiStudio.GetPrefabPathForScreen(screen);

                if (string.IsNullOrEmpty(prefabPath) || !AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath))
                {
                    Debug.Log("[UIViewEditor] No prefab for " + screen + " at " + prefabPath);
                    skipped++;
                    continue;
                }

                string prefabName = System.IO.Path.GetFileNameWithoutExtension(prefabPath);

                GameObject contents = PrefabUtility.LoadPrefabContents(prefabPath);
                if (contents == null)
                {
                    skipped++;
                    continue;
                }

                try
                {
                    View viewComponent = contents.GetComponent<View>();
                    if (viewComponent == null)
                    {
                        skipped++;
                        continue;
                    }

                    Type type = viewComponent.GetType();
                    if (!HasBindReferencesMethod(type))
                    {
                        skipped++;
                        continue;
                    }

                    InvokeBindReferences(viewComponent);
                    SmartFallbackPopulate(viewComponent);

                    // Report null fields BEFORE saving, while the component is guaranteed valid
                    string nullReport = GetNullFieldReportString(viewComponent);
                    bool allPopulated = string.IsNullOrEmpty(nullReport);

                    PrefabUtility.SaveAsPrefabAsset(contents, prefabPath);
                    populated++;

                    if (!allPopulated)
                        Debug.LogWarning("[UIViewEditor] " + prefabName + " still has null fields: " + nullReport, contents);
                    else
                        Debug.Log("[UIViewEditor] Populated " + prefabName + " (" + type.Name + ")", contents);
                }
                catch (Exception ex)
                {
                    Debug.LogError("[UIViewEditor] Failed to populate " + prefabName + ": " + ex.Message);
                    errors++;
                }
                finally
                {
                    PrefabUtility.UnloadPrefabContents(contents);
                }
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog("Populate All UI References",
                "Completed!\n\n" +
                "Populated: " + populated + "\n" +
                "Skipped: " + skipped + "\n" +
                "Errors: " + errors,
                "OK");
        }
    }
}
