using System;
using System.Collections.Generic;

namespace RingFlow.Gameplay
{
    /// <summary>
    /// Ring type enum. Values are serialized by ordinal — only append new values.
    /// Do not reorder or remove entries; mark deprecated values with [Obsolete].
    /// </summary>
    public enum RingType
    {
        Standard = 0,
        /// <summary>Deprecated alias for <see cref="Locked"/>. Only kept for save compatibility.</summary>
        [Obsolete("Use RingType.Locked instead. Kept for serialization backward compat.")]
        Key,
        Mystery,
        Frozen,
        /// <summary>
        /// Key ring that unlocks a locked pole when placed on it.
        /// Despite the name, this is the KEY (not the locked state of a pole).
        /// Named "Locked" for historical serialization compatibility.
        /// </summary>
        Locked,
        Stone,
        Glass,
        Rainbow,
        Bomb,
        Chain,
        Magnet,
        Paint
    }

    [Serializable]
    public struct RingData
    {
        public RingColor Color;
        public RingType Type;
        public int AdditionalData; // bomb sayacı, kilit ID'si vb. ek veriler için

        public RingData(RingColor color, RingType type = RingType.Standard, int additionalData = 0)
        {
            Color = color;
            Type = type;
            AdditionalData = additionalData;
        }

        public RingData Clone()
        {
            return new RingData(Color, Type, AdditionalData);
        }
    }

    [Serializable]
    public class PoleData
    {
        public int RingCapacity;
        public List<RingData> Rings = new();
        public bool IsLocked;
        public int PortalTargetId = -1;
        public string CapacityText => $"{RingCapacity}";

        public PoleData() { }

        public PoleData(int ringCapacity)
        {
            RingCapacity = ringCapacity;
        }
    }

    [Serializable]
    public class LevelData
    {
        public int LevelIndex;
        public int Seed;
        public int TargetMoves;
        public List<PoleData> Poles = new();

        // Canonical metadata generated by LevelGenerator and consumed by replay,
        // save, and validation tooling.
        public string LevelType;
        public int PoleCount;
        public int PoleCapacity;
        public int ColorCount;
        public int EmptyPoleCount;
        public int PortalCount;
        public float DifficultyScore;
        public bool IsTutorial;
        public List<string> RuleReferences = new();
        public bool IsChallenge;
        public string ProgressionFlags;
    }

    public static class RingTypeExtensions
    {
        private const int LegacyKeyValue = 1;

        public static bool IsLegacyKey(this RingType type)
        {
            return (int)type == LegacyKeyValue;
        }

        public static bool IsLockedKey(this RingType type)
        {
            return type == RingType.Locked || type.IsLegacyKey();
        }
    }
}
