using System;
using System.Collections.Generic;

namespace RingFlow.Gameplay
{
    /// <summary>
    /// Ring type enum. Values are serialized — never reorder or remove existing values.
    /// </summary>
    public enum RingType
    {
        Standard = 0,
        /// <summary>Key ring (alias for Locked). Use <see cref="Locked"/> for new code.</summary>
        Key,
        Mystery,
        Frozen,
        /// <summary>
        /// Key ring that unlocks a locked pole when placed on it.
        /// Named "Locked" for historical serialization compatibility — represents
        /// the KEY that unlocks, not the pole state.
        /// </summary>
        Locked,
        Stone,
        Glass,
        Rainbow,
        Bomb,
        Chain,
        Magnet,
        Paint,
        Ghost
    }

    [Serializable]
    public struct RingData
    {
        public RingColor Color;
        public RingType Type;
        public int AdditionalData; // bomb sayacı, kilit ID'si vb. ek veriler için

        public RingData(RingColor color, RingType type = RingType.Standard, int additionalData = 0)
        {
            Color = color;
            Type = type;
            AdditionalData = additionalData;
        }

        public RingData Clone()
        {
            return new RingData(Color, Type, AdditionalData);
        }
    }

    [Serializable]
    public class PoleData
    {
        public int RingCapacity;
        public List<RingData> Rings = new();
        public bool IsLocked;
        public int PortalTargetId = -1;
        public string CapacityText => $"{RingCapacity}";

        public PoleData() { }

        public PoleData(int ringCapacity)
        {
            RingCapacity = ringCapacity;
        }
    }

    [Serializable]
    public class LevelData
    {
        public int LevelIndex;
        public int Seed;
        public int TargetMoves;
        public List<PoleData> Poles = new();

        // Canonical metadata generated by LevelGenerator and consumed by replay,
        // save, and validation tooling.
        public string LevelType;
        public int PoleCount;
        public int PoleCapacity;
        public int ColorCount;
        public int EmptyPoleCount;
        public int PortalCount;
        public float DifficultyScore;
        public bool IsTutorial;
        public List<string> RuleReferences = new();
        public bool IsChallenge;
        public string ProgressionFlags;
    }
}

